export default  {
  "light": {
    "--hsl-primary": "192, 100%, 25%",
    "--color-primary": "hsla(var(--hsl-primary), 1)",
    "--hsl-on-primary": "0, 0%, 100%",
    "--color-on-primary": "hsla(var(--hsl-on-primary), 1)",
    "--hsl-primary-container": "199, 100%, 87%",
    "--color-primary-container": "hsla(var(--hsl-primary-container), 1)",
    "--hsl-on-primary-container": "195, 100%, 8%",
    "--color-on-primary-container": "hsla(var(--hsl-on-primary-container), 1)",
    "--hsl-info": "199, 17%, 36%",
    "--color-info": "hsla(var(--hsl-info), 1)",
    "--hsl-on-info": "0, 0%, 100%",
    "--color-on-info": "hsla(var(--hsl-on-info), 1)",
    "--hsl-info-container": "201, 57%, 88%",
    "--color-info-container": "hsla(var(--hsl-info-container), 1)",
    "--hsl-on-info-container": "197, 66%, 9%",
    "--color-on-info-container": "hsla(var(--hsl-on-info-container), 1)",
    "--hsl-warning": "242, 16%, 42%",
    "--color-warning": "hsla(var(--hsl-warning), 1)",
    "--hsl-on-warning": "0, 0%, 100%",
    "--color-on-warning": "hsla(var(--hsl-on-warning), 1)",
    "--hsl-warning-container": "246, 100%, 94%",
    "--color-warning-container": "hsla(var(--hsl-warning-container), 1)",
    "--hsl-on-warning-container": "242, 39%, 15%",
    "--color-on-warning-container": "hsla(var(--hsl-on-warning-container), 1)",
    "--hsl-danger": "0, 75%, 42%",
    "--color-danger": "hsla(var(--hsl-danger), 1)",
    "--hsl-on-danger": "0, 0%, 100%",
    "--color-on-danger": "hsla(var(--hsl-on-danger), 1)",
    "--hsl-danger-container": "6, 100%, 92%",
    "--color-danger-container": "hsla(var(--hsl-danger-container), 1)",
    "--hsl-on-danger-container": "358, 100%, 13%",
    "--color-on-danger-container": "hsla(var(--hsl-on-danger-container), 1)",
    "--hsl-body": "220, 60%, 99%",
    "--color-body": "hsla(var(--hsl-body), 1)",
    "--hsl-text": "204, 9%, 11%",
    "--color-text": "hsla(var(--hsl-text), 1)",
    "--hsl-on-surface-variant": "200, 9%, 27%",
    "--color-on-surface-variant": "hsla(var(--hsl-on-surface-variant), 1)",
    "--hsl-outline": "203, 5%, 46%",
    "--color-outline": "hsla(var(--hsl-outline), 1)",
    "--hsl-inverse-surface": "195, 4%, 19%",
    "--color-inverse-surface": "hsla(var(--hsl-inverse-surface), 1)"
  },
  "dark": {
    "--hsl-primary": "196, 100%, 69%",
    "--color-primary": "hsla(var(--hsl-primary), 1)",
    "--hsl-on-primary": "194, 100%, 14%",
    "--color-on-primary": "hsla(var(--hsl-on-primary), 1)",
    "--hsl-primary-container": "193, 100%, 19%",
    "--color-primary-container": "hsla(var(--hsl-primary-container), 1)",
    "--hsl-on-primary-container": "199, 100%, 87%",
    "--color-on-primary-container": "hsla(var(--hsl-on-primary-container), 1)",
    "--hsl-info": "200, 28%, 77%",
    "--color-info": "hsla(var(--hsl-info), 1)",
    "--hsl-on-info": "198, 33%, 18%",
    "--color-on-info": "hsla(var(--hsl-on-info), 1)",
    "--hsl-info-container": "198, 22%, 27%",
    "--color-info-container": "hsla(var(--hsl-info-container), 1)",
    "--hsl-on-info-container": "201, 57%, 88%",
    "--color-on-info-container": "hsla(var(--hsl-on-info-container), 1)",
    "--hsl-warning": "243, 48%, 84%",
    "--color-warning": "hsla(var(--hsl-warning), 1)",
    "--hsl-on-warning": "242, 26%, 24%",
    "--color-on-warning": "hsla(var(--hsl-on-warning), 1)",
    "--hsl-warning-container": "242, 20%, 33%",
    "--color-warning-container": "hsla(var(--hsl-warning-container), 1)",
    "--hsl-on-warning-container": "246, 100%, 94%",
    "--color-on-warning-container": "hsla(var(--hsl-on-warning-container), 1)",
    "--hsl-danger": "6, 100%, 84%",
    "--color-danger": "hsla(var(--hsl-danger), 1)",
    "--hsl-on-danger": "357, 100%, 21%",
    "--color-on-danger": "hsla(var(--hsl-on-danger), 1)",
    "--hsl-danger-container": "356, 100%, 29%",
    "--color-danger-container": "hsla(var(--hsl-danger-container), 1)",
    "--hsl-on-danger-container": "6, 100%, 84%",
    "--color-on-danger-container": "hsla(var(--hsl-on-danger-container), 1)",
    "--hsl-body": "204, 9%, 11%",
    "--color-body": "hsla(var(--hsl-body), 1)",
    "--hsl-text": "200, 5%, 89%",
    "--color-text": "hsla(var(--hsl-text), 1)",
    "--hsl-on-surface-variant": "200, 11%, 78%",
    "--color-on-surface-variant": "hsla(var(--hsl-on-surface-variant), 1)",
    "--hsl-outline": "200, 5%, 56%",
    "--color-outline": "hsla(var(--hsl-outline), 1)",
    "--hsl-inverse-surface": "200, 5%, 89%",
    "--color-inverse-surface": "hsla(var(--hsl-inverse-surface), 1)"
  }
}